INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'ACDOCA', 'Universal Journal', 'FI/CO', 1, 'conformed.fact_finance_actual (conceptually closest)');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'BKPF', 'Accounting Document Header', 'FI', 1, 'sap_raw.fi_documents');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'BSEG', 'Accounting Document Segment', 'FI', 1, 'sap_raw.fi_document_lines');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'BSET', 'Tax Data Document Segment', 'FI', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'BSIS', 'G/L Open/Index Items', 'FI', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'BSAS', 'G/L Cleared/Index Items', 'FI', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'BSID', 'Customer Open Items', 'FI-AR', 1, 'conformed.fact_ar_aging (aggregated, not open-item level)');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'BSAD', 'Customer Cleared Items', 'FI-AR', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'BSIK', 'Vendor Open Items', 'FI-AP', 1, 'conformed.fact_ap_aging (aggregated, not open-item level)');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'BSAK', 'Vendor Cleared Items', 'FI-AP', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'FAGLFLEXA', 'New GL Actual Line Items', 'FI', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'FAGLFLEXT', 'New GL Totals', 'FI', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'COBK', 'CO Document Header', 'CO', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'COEP', 'CO Line Items', 'CO', 1, 'conformed.fact_finance_actual (CO grain, conceptually)');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'COSP', 'CO Totals', 'CO', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'COSS', 'CO Totals Secondary', 'CO', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'CSKA', 'Cost Element Master', 'CO', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'CSKB', 'Cost Element Company Code', 'CO', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'CSKS', 'Cost Center Master', 'CO', 1, 'conformed.dim_cost_center');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'CSKT', 'Cost Center Text', 'CO', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'CEPC', 'Profit Center Master', 'CO', 1, 'conformed.dim_profit_center');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'CEPCT', 'Profit Center Text', 'CO', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'AUFK', 'Order Master', 'CO/PP/PM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'AFKO', 'Production Order Header', 'PP', 1, 'sap_raw.production_orders_raw');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'AFPO', 'Production Order Item', 'PP', 1, 'sap_raw.production_orders_raw');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'AFVC', 'Order Operation', 'PP', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'AFVV', 'Operation Quantities/Dates', 'PP', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'AFRU', 'Confirmation', 'PP', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'AFIH', 'Maintenance Order Header', 'PM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'ILOA', 'Location/Account Assignment', 'PM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'EQUI', 'Equipment Master', 'PM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'EQKT', 'Equipment Text', 'PM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'IFLOT', 'Functional Location', 'PM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'IFLOTX', 'Functional Location Text', 'PM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'QMEL', 'Quality Notification', 'QM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'QALS', 'Inspection Lot', 'QM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'QAMV', 'Inspection Characteristic', 'QM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'QAVE', 'Usage Decision', 'QM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'MARA', 'Material Master General', 'MM', 1, 'conformed.dim_product');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'MAKT', 'Material Text', 'MM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'MARC', 'Material Plant', 'MM', 1, 'conformed.dim_product (plant view, partial)');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'MARD', 'Storage Location Stock', 'MM', 1, 'conformed.fact_inventory (partial, no storage-location split)');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'MBEW', 'Material Valuation', 'MM', 1, 'conformed.fact_inventory (valuation folded in)');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'MBEWH', 'Material Valuation History', 'MM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'MATDOC', 'Material Documents', 'MM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'MKPF', 'Material Document Header', 'MM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'MCHA', 'Batch Master', 'MM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'MCH1', 'Batch Master Cross-Plant', 'MM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'MCHB', 'Batch Stock', 'MM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'MCHBH', 'Batch Stock History', 'MM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'MSKA', 'Sales Order Stock', 'MM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'MSKU', 'Customer Stock', 'MM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'MSLB', 'Vendor Consignment Stock', 'MM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'MSPR', 'Project Stock', 'MM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'EKKO', 'Purchase Order Header', 'MM-PUR', 1, 'conformed.fact_purchase_order (header+item combined)');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'EKPO', 'Purchase Order Item', 'MM-PUR', 1, 'conformed.fact_purchase_order (header+item combined)');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'EKET', 'PO Schedule Lines', 'MM-PUR', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'EKKN', 'PO Account Assignment', 'MM-PUR', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'EKBE', 'PO History', 'MM-PUR', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'EKES', 'Supplier Confirmations', 'MM-PUR', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'EINA', 'Purchasing Info Record General', 'MM-PUR', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'EINE', 'Purchasing Info Record Purchasing Org', 'MM-PUR', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'LFA1', 'Vendor General', 'MM/AP', 1, 'conformed.dim_vendor');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'LFB1', 'Vendor Company Code', 'AP', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'LFM1', 'Vendor Purchasing Org', 'MM-PUR', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'KNA1', 'Customer General', 'SD/AR', 1, 'conformed.dim_customer');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'KNB1', 'Customer Company Code', 'AR', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'KNVV', 'Customer Sales Area', 'SD', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'KNVP', 'Customer Partner Functions', 'SD', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'BUT000', 'Business Partner General', 'BP', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'BUT100', 'Business Partner Roles', 'BP', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'BUT020', 'Business Partner Addresses', 'BP', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'ADRC', 'Address Master', 'Cross', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'T001', 'Company Code', 'FI', 1, 'conformed.dim_company');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'T001W', 'Plant', 'MM/PP', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'T001L', 'Storage Location', 'MM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'T009', 'Fiscal Year Variant', 'FI', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'T009B', 'Fiscal Year Periods', 'FI', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'T003', 'Document Types', 'FI', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'T003T', 'Document Type Text', 'FI', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'SKA1', 'G/L Account Chart of Accounts', 'FI', 1, 'conformed.dim_gl_account');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'SKAT', 'G/L Account Text', 'FI', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'SKB1', 'G/L Account Company Code', 'FI', 1, 'conformed.dim_gl_account');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'T004', 'Chart of Accounts', 'FI', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'TGSB', 'Business Area', 'FI', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'TGSBT', 'Business Area Text', 'FI', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'T005', 'Countries', 'Cross', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'T005T', 'Country Text', 'Cross', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'T006', 'Units of Measure', 'MM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'T006A', 'Units of Measure Text', 'MM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'T024', 'Purchasing Groups', 'MM-PUR', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'T024E', 'Purchasing Organizations', 'MM-PUR', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'T161', 'Purchasing Document Types', 'MM-PUR', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'T163', 'Item Categories', 'MM-PUR', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'T023', 'Material Groups', 'MM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'T023T', 'Material Group Text', 'MM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'T179', 'Product Hierarchy', 'SD/MM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'T179T', 'Product Hierarchy Text', 'SD/MM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'T134', 'Material Types', 'MM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'T134T', 'Material Type Text', 'MM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'T001K', 'Valuation Area', 'MM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'T025', 'Valuation Classes', 'MM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'T685', 'Pricing Conditions Types', 'SD', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'T685T', 'Pricing Condition Type Text', 'SD', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'A305', 'Pricing Condition Records Example', 'SD', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'KONP', 'Condition Items', 'SD', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'KONH', 'Condition Headers', 'SD', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'PRCD_ELEMENTS', 'Pricing Elements', 'SD', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'KONV', 'Pricing Conditions Legacy', 'SD', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'VBFA', 'Document Flow', 'SD', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'VBAK', 'Sales Order Header', 'SD', 1, 'sap_raw.sales_orders');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'VBAP', 'Sales Order Item', 'SD', 1, 'sap_raw.sales_order_items');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'VBEP', 'Sales Schedule Line', 'SD', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'VBKD', 'Sales Business Data', 'SD', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'VBPA', 'Sales Document Partners', 'SD', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'VBUK', 'Sales Document Header Status', 'SD', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'VBUP', 'Sales Document Item Status', 'SD', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'LIKP', 'Delivery Header', 'LE', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'LIPS', 'Delivery Item', 'LE', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'VLPKM', 'Delivery/Handling Related', 'LE', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'VBRK', 'Billing Header', 'SD-Billing', 1, 'sap_raw.billing_documents');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'VBRP', 'Billing Item', 'SD-Billing', 1, 'sap_raw.billing_items');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'RSEG', 'Invoice Receipt Item', 'MM-IV', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'RBKP', 'Invoice Receipt Header', 'MM-IV', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'ESSR', 'Service Entry Sheet', 'MM-SRV', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'ESLL', 'Service Package Lines', 'MM-SRV', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'ESLH', 'Service Package Header', 'MM-SRV', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'PRPS', 'WBS Element', 'PS', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'PROJ', 'Project Definition', 'PS', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'COBRB', 'Settlement Rule', 'CO/PS', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'BPBK', 'Budget/Plan Header', 'PS', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'BPGE', 'Budget Values', 'PS', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'BPJA', 'Budget Annual Values', 'PS', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'BPPE', 'Budget Period Values', 'PS', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'ANLA', 'Asset Master General', 'FI-AA', 1, 'conformed.fact_capex (partial)');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'ANLB', 'Asset Depreciation Terms', 'FI-AA', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'ANLC', 'Asset Value Fields', 'FI-AA', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'ANEK', 'Asset Document Header', 'FI-AA', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'ANEP', 'Asset Line Items', 'FI-AA', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'ANEA', 'Asset Proportional Values', 'FI-AA', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'ANLP', 'Asset Periodic Values', 'FI-AA', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'ANLU', 'Asset Master Origin', 'FI-AA', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'FAAT_DOC_IT', 'Asset Accounting Document Items', 'FI-AA', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'FAAT_DOC_IT_AA', 'Asset Accounting Document Items', 'FI-AA', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'T093', 'Asset Accounting Config', 'FI-AA', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'T093B', 'Depreciation Areas', 'FI-AA', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'T095', 'Asset Class Account Determination', 'FI-AA', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'T096', 'Asset Class Account Determination', 'FI-AA', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'CKMLHD', 'Material Ledger Header', 'CO-ML', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'CKMLPP', 'Material Ledger Period Data', 'CO-ML', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'CKMLCR', 'Material Ledger Currency Data', 'CO-ML', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'MLHD', 'Material Ledger Header Legacy', 'CO-ML', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'MLIT', 'Material Ledger Items', 'CO-ML', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'MLCR', 'Material Ledger Currencies', 'CO-ML', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'MLCD', 'Material Ledger Documents', 'CO-ML', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'CKMI1', 'Material Ledger Price History', 'CO-ML', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'MSEG', 'Material Document Segment Legacy', 'MM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'MSTQ', 'Stock Quantity', 'MM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'MSTB', 'Stock Value', 'MM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'MSSA', 'Special Stock Aggregates', 'MM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'MSSQ', 'Special Stock Quantity', 'MM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'MSSL', 'Special Stock by Storage Location', 'MM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'MVKE', 'Material Sales Data', 'SD', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'MLGN', 'Warehouse Material', 'EWM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'MLGT', 'Warehouse Material Storage Type', 'EWM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'LQUA', 'Quant', 'EWM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'LTAP', 'Transfer Order Item', 'LE-WM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'LTAK', 'Transfer Order Header', 'LE-WM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'VEKP', 'Handling Unit Header', 'LE', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'VEPO', 'Handling Unit Item', 'LE', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'STKO', 'BOM Header', 'PP', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'STPO', 'BOM Item', 'PP', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'MAST', 'Material to BOM Link', 'PP', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'STAS', 'BOM Item Selection', 'PP', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'PLKO', 'Routing Header', 'PP', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'PLPO', 'Routing Operation', 'PP', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'MAPL', 'Material Routing Assignment', 'PP', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'PLMZ', 'Routing Assignment', 'PP', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'CRHD', 'Work Center Header', 'PP', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'CRTX', 'Work Center Text', 'PP', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'KAKO', 'Capacity Header', 'PP', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'KBED', 'Capacity Requirements', 'PP', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'RESB', 'Reservation/Dependent Requirement', 'PP/MM', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'MDKP', 'MRP Header', 'PP-MRP', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'MDTB', 'MRP Table', 'PP-MRP', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'PLAF', 'Planned Order', 'PP-MRP', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'PBIM', 'Independent Requirements', 'PP-MRP', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'PBED', 'Independent Requirement Data', 'PP-MRP', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'MDSB', 'Dependent Requirements', 'PP-MRP', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'VBBE', 'Sales Requirements', 'PP-MRP', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'MDVM', 'MRP Planning File', 'PP-MRP', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'SWWWIHEAD', 'Workflow Work Item Header', 'Workflow', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'SWWLOGHIST', 'Workflow History', 'Workflow', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'TSTC', 'Transaction Codes', 'Basis', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'DD02L', 'Table Definitions', 'DDIC', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('SAP', 'DD03L', 'Table Fields', 'DDIC', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'TENANT', 'Tenant', 'Platform', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'WORKSPACE', 'Workspace', 'Platform', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'MODEL', 'Model', 'Platform', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'MODULE', 'Module', 'Metadata', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'VIEW', 'Saved View', 'Metadata', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'LIST', 'List', 'Metadata', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'LIST_ITEM', 'List Item', 'Master Data', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'LIST_PROPERTY', 'List Property', 'Master Data', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'LINE_ITEM', 'Line Item', 'Metadata', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'LINE_ITEM_FORMULA', 'Line Item Formula', 'Metadata', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'LINE_ITEM_FORMAT', 'Line Item Format', 'Metadata', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'DIMENSION', 'Dimension', 'Metadata', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'TIME_DIMENSION', 'Time Dimension', 'Planning', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'VERSION', 'Version', 'Planning', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'IMPORT', 'Import', 'Integration', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'EXPORT', 'Export', 'Integration', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'ACTION', 'Action', 'Integration', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'PROCESS', 'Process', 'Integration', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'FILE', 'File', 'Integration', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'WORKFLOW', 'Workflow', 'Planning', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'USER', 'User', 'Security', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'ROLE', 'Role', 'Security', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'SELECTIVE_ACCESS', 'Selective Access', 'Security', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'MODEL_CALENDAR', 'Model Calendar', 'Planning', 1, 'conformed.dim_date');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'ORG_HIERARCHY', 'Organization Hierarchy', 'Planning', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'GEOGRAPHY', 'Geography', 'Planning', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'CURRENCY', 'Currency', 'Planning', 1, 'conformed.fx_rate');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'SCENARIO', 'Scenario', 'Planning', 1, 'conformed.dim_scenario');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'ASSUMPTION', 'Assumption', 'Planning', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'DRIVER', 'Planning Driver', 'Planning', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'GL_ACCOUNT', 'G/L Account', 'Finance Planning', 1, 'conformed.dim_gl_account');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'COST_CENTER', 'Cost Center', 'Finance Planning', 1, 'conformed.dim_cost_center');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'PROFIT_CENTER', 'Profit Center', 'Finance Planning', 1, 'conformed.dim_profit_center');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'LEGAL_ENTITY', 'Legal Entity', 'Finance Planning', 1, 'conformed.dim_company');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'PLANT', 'Plant', 'Supply Planning', 1, 'conformed.dim_plant');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'PRODUCT', 'Product', 'Supply Planning', 1, 'conformed.dim_product');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'CUSTOMER', 'Customer', 'Commercial Planning', 1, 'conformed.dim_customer');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'VENDOR', 'Vendor', 'Procurement Planning', 1, 'conformed.dim_vendor');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'REVENUE_PLAN', 'Revenue Plan', 'Finance', 1, 'conformed.fact_sales_plan (planned_revenue)');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'COGS_PLAN', 'COGS Plan', 'Finance', 1, 'conformed.fact_finance_plan (GL-4000 budget)');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'OPEX_PLAN', 'Opex Plan', 'Finance', 1, 'conformed.fact_finance_plan (GL-6100/6300 budget)');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'EBITDA_PLAN', 'EBITDA Plan', 'Finance', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'CAPEX_PLAN', 'Capex Plan', 'Finance', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'CASH_FLOW_PLAN', 'Cash Flow Plan', 'Finance', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'AR_PLAN', 'AR Plan', 'Working Capital', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'AP_PLAN', 'AP Plan', 'Working Capital', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'WORKING_CAPITAL_PLAN', 'Working Capital Plan', 'Working Capital', 1, 'conformed.fact_working_capital_plan');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'MARGIN_PLAN', 'Margin Plan', 'Finance', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'PRICE_PLAN', 'Price Plan', 'Commercial', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'SALES_PLAN', 'Sales Plan', 'Commercial', 1, 'conformed.fact_sales_plan');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'DEMAND_PLAN', 'Demand Plan', 'Supply Chain', 1, 'conformed.fact_sales_plan (FORECAST scenario, proxy)');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'SUPPLY_PLAN', 'Supply Plan', 'Supply Chain', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'PRODUCTION_PLAN', 'Production Plan', 'Manufacturing', 1, 'conformed.fact_production_plan');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'CAPACITY_PLAN', 'Capacity Plan', 'Manufacturing', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'INVENTORY_PLAN', 'Inventory Plan', 'Supply Chain', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'PURCHASE_PLAN', 'Purchase Plan', 'Procurement', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'PURCHASE_PRICE_PLAN', 'Purchase Price Plan', 'Procurement', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'HEADCOUNT_PLAN', 'Headcount Plan', 'Workforce', 1, 'conformed.fact_headcount_plan');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'LABOR_COST_PLAN', 'Labor Cost Plan', 'Workforce', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'S&OP_PLAN', 'S&OP Plan', 'Supply Chain', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'FORECAST', 'Forecast', 'Planning', 1, 'conformed.fact_sales_plan (FORECAST scenario)');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'BUDGET', 'Budget', 'Planning', 1, 'conformed.fact_sales_plan / fact_finance_plan (BUDGET scenario)');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'ACTUALS_LOAD', 'Actuals Load', 'Integration', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'KPI_TARGET', 'KPI Target', 'Performance', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'ALLOCATION', 'Allocation', 'Planning', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'STATISTICAL_FORECAST', 'Statistical Forecast', 'Planning', 0, NULL);
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'FORECAST_ACCURACY', 'Forecast Accuracy', 'Performance', 1, 'lib/queries.ts: forecast_performance');
INSERT INTO conformed.source_table_catalog (source_system, code, description, domain, implemented, implemented_as) VALUES ('ANAPLAN', 'VARIANCE', 'Plan Actual Variance', 'Performance', 1, 'conformed.sales_performance / finance_performance (variance columns)');
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('Company', 'Business entity/legal entity', 'SAP+Anaplan', 1, 'conformed.dim_company');
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('Plant', 'Manufacturing/location', 'SAP+Anaplan', 1, 'conformed.dim_plant');
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('ProfitCenter', 'Profitability responsibility', 'SAP+Anaplan', 1, 'conformed.dim_profit_center');
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('CostCenter', 'Cost ownership', 'SAP+Anaplan', 1, 'conformed.dim_cost_center');
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('GLAccount', 'Financial account', 'SAP+Anaplan', 1, 'conformed.dim_gl_account');
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('FiscalPeriod', 'Fiscal time', 'SAP+Anaplan', 1, 'conformed.dim_date');
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('Customer', 'Customer', 'SAP+Anaplan', 1, 'conformed.dim_customer');
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('Vendor', 'Vendor', 'SAP+Anaplan', 1, 'conformed.dim_vendor');
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('Material', 'Product/material', 'SAP+Anaplan', 1, 'conformed.dim_product');
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('Inventory', 'Inventory position', 'SAP', 1, 'conformed.fact_inventory');
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('PurchaseOrder', 'Procurement commitment', 'SAP', 1, 'conformed.fact_purchase_order');
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('InvoiceReceipt', 'Supplier invoice', 'SAP', 0, NULL);
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('SalesOrder', 'Customer order', 'SAP', 1, 'sap_raw.sales_orders');
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('Delivery', 'Outbound delivery', 'SAP', 0, NULL);
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('BillingDocument', 'Customer billing', 'SAP', 1, 'sap_raw.billing_documents');
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('RevenuePosting', 'Revenue accounting', 'SAP', 0, NULL);
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('AccountingDocument', 'Journal/accounting document', 'SAP', 0, NULL);
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('AccountingItem', 'Journal item', 'SAP', 0, NULL);
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('COItem', 'CO line item', 'SAP', 0, NULL);
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('ProductionOrder', 'Production order', 'SAP', 1, 'conformed.fact_production_order');
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('ProductionOperation', 'Production operation', 'SAP', 0, NULL);
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('Confirmation', 'Production confirmation', 'SAP', 0, NULL);
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('Equipment', 'Asset/equipment', 'SAP', 0, NULL);
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('FunctionalLocation', 'Functional location', 'SAP', 0, NULL);
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('MaintenanceOrder', 'Maintenance order', 'SAP', 0, NULL);
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('QualityNotification', 'Quality issue', 'SAP', 0, NULL);
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('InspectionLot', 'Inspection lot', 'SAP', 0, NULL);
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('Asset', 'Fixed asset', 'SAP', 0, NULL);
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('Project', 'Project', 'SAP', 0, NULL);
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('WBSElement', 'WBS element', 'SAP', 0, NULL);
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('Plan', 'Planning model', 'Anaplan', 0, NULL);
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('Forecast', 'Forecast', 'Anaplan', 0, NULL);
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('Scenario', 'Scenario', 'Anaplan', 0, NULL);
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('PlanningDriver', 'Planning driver', 'Anaplan', 0, NULL);
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('DemandPlan', 'Demand plan', 'Anaplan', 0, NULL);
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('SupplyPlan', 'Supply plan', 'Anaplan', 0, NULL);
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('ProductionPlan', 'Production plan', 'Anaplan', 0, NULL);
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('InventoryPlan', 'Inventory plan', 'Anaplan', 0, NULL);
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('RevenuePlan', 'Revenue plan', 'Anaplan', 0, NULL);
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('COGSPlan', 'COGS plan', 'Anaplan', 0, NULL);
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('OpexPlan', 'Opex plan', 'Anaplan', 0, NULL);
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('CashPlan', 'Cash plan', 'Anaplan', 0, NULL);
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('ARPlan', 'AR plan', 'Anaplan', 0, NULL);
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('APPlan', 'AP plan', 'Anaplan', 0, NULL);
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('CapexPlan', 'Capex plan', 'Anaplan', 0, NULL);
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('MarginPlan', 'Margin plan', 'Anaplan', 0, NULL);
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('CapacityPlan', 'Capacity plan', 'Anaplan', 0, NULL);
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('Variance', 'Actual-plan variance', 'Conformed', 0, NULL);
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('Risk', 'Risk', 'Conformed', 0, NULL);
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('Metric', 'Business metric', 'Semantic', 0, NULL);
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('SourceTable', 'Physical source table', 'Metadata', 0, NULL);
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('AnaplanModule', 'Anaplan module', 'Metadata', 0, NULL);
INSERT INTO conformed.ontology_entity_catalog (entity, description, source, implemented, implemented_as) VALUES ('AnaplanLineItem', 'Anaplan line item', 'Metadata', 0, NULL);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Company', 'HAS_PLANT', 'Plant', 1);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Company', 'HAS_GL_ACCOUNT', 'GLAccount', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Plant', 'HAS_PROFIT_CENTER', 'ProfitCenter', 1);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('ProfitCenter', 'HAS_COST_CENTER', 'CostCenter', 1);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('CostCenter', 'POSTS_TO', 'GLAccount', 1);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('AccountingDocument', 'HAS_ITEM', 'AccountingItem', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('AccountingItem', 'USES_GL', 'GLAccount', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('AccountingItem', 'FOR_COST_CENTER', 'CostCenter', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('AccountingItem', 'FOR_PROFIT_CENTER', 'ProfitCenter', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('AccountingItem', 'FOR_PLANT', 'Plant', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('COItem', 'FOR_COST_CENTER', 'CostCenter', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('COItem', 'FOR_PROFIT_CENTER', 'ProfitCenter', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('COItem', 'FOR_INTERNAL_ORDER', 'ProductionOrder', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Plant', 'HAS_MATERIAL', 'Material', 1);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Material', 'STORED_AT', 'Inventory', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Material', 'HAS_PURCHASE_ORDER', 'PurchaseOrder', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Vendor', 'SUPPLIES', 'Material', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Vendor', 'HAS_PURCHASE_ORDER', 'PurchaseOrder', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('PurchaseOrder', 'HAS_INVOICE', 'InvoiceReceipt', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('PurchaseOrder', 'FOR_MATERIAL', 'Material', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Customer', 'HAS_SALES_ORDER', 'SalesOrder', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('SalesOrder', 'HAS_DELIVERY', 'Delivery', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('SalesOrder', 'HAS_BILLING', 'BillingDocument', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Delivery', 'HAS_BILLING', 'BillingDocument', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('BillingDocument', 'POSTS_TO', 'RevenuePosting', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Customer', 'HAS_AR', 'AccountingItem', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Vendor', 'HAS_AP', 'AccountingItem', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Plant', 'HAS_PRODUCTION_ORDER', 'ProductionOrder', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('ProductionOrder', 'HAS_OPERATION', 'ProductionOperation', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('ProductionOrder', 'HAS_CONFIRMATION', 'Confirmation', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Material', 'HAS_PRODUCTION_ORDER', 'ProductionOrder', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Equipment', 'LOCATED_AT', 'FunctionalLocation', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('MaintenanceOrder', 'FOR_EQUIPMENT', 'Equipment', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('MaintenanceOrder', 'FOR_FUNCTIONAL_LOCATION', 'FunctionalLocation', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('QualityNotification', 'FOR_MATERIAL', 'Material', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('InspectionLot', 'FOR_MATERIAL', 'Material', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Asset', 'BELONGS_TO', 'Company', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Project', 'HAS_WBS', 'WBSElement', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Plan', 'HAS_REVENUE_PLAN', 'RevenuePlan', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Plan', 'HAS_COGS_PLAN', 'COGSPlan', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Plan', 'HAS_OPEX_PLAN', 'OpexPlan', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Plan', 'HAS_CASH_PLAN', 'CashPlan', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Plan', 'HAS_AR_PLAN', 'ARPlan', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Plan', 'HAS_AP_PLAN', 'APPlan', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Plan', 'HAS_CAPEX_PLAN', 'CapexPlan', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Plan', 'HAS_MARGIN_PLAN', 'MarginPlan', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Plan', 'HAS_DEMAND_PLAN', 'DemandPlan', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Plan', 'HAS_SUPPLY_PLAN', 'SupplyPlan', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Plan', 'HAS_PRODUCTION_PLAN', 'ProductionPlan', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Plan', 'HAS_INVENTORY_PLAN', 'InventoryPlan', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Plan', 'HAS_CAPACITY_PLAN', 'CapacityPlan', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Plan', 'USES_SCENARIO', 'Scenario', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Scenario', 'HAS_DRIVER', 'PlanningDriver', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('PlanningDriver', 'DRIVES', 'RevenuePlan', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('PlanningDriver', 'DRIVES', 'COGSPlan', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('PlanningDriver', 'DRIVES', 'DemandPlan', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('PlanningDriver', 'DRIVES', 'SupplyPlan', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('PlanningDriver', 'DRIVES', 'ProductionPlan', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('PlanningDriver', 'DRIVES', 'InventoryPlan', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('RevenuePlan', 'FOR_PLANT', 'Plant', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('RevenuePlan', 'FOR_CUSTOMER', 'Customer', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('RevenuePlan', 'FOR_PERIOD', 'FiscalPeriod', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('COGSPlan', 'FOR_PLANT', 'Plant', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('COGSPlan', 'FOR_MATERIAL', 'Material', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('OpexPlan', 'FOR_COST_CENTER', 'CostCenter', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('DemandPlan', 'FOR_CUSTOMER', 'Customer', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('DemandPlan', 'FOR_MATERIAL', 'Material', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('SupplyPlan', 'FOR_MATERIAL', 'Material', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('ProductionPlan', 'FOR_PLANT', 'Plant', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('ProductionPlan', 'FOR_MATERIAL', 'Material', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('InventoryPlan', 'FOR_PLANT', 'Plant', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('InventoryPlan', 'FOR_MATERIAL', 'Material', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Variance', 'COMPARES', 'AccountingItem', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Variance', 'COMPARES', 'RevenuePlan', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Variance', 'COMPARES', 'COGSPlan', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Variance', 'DRIVEN_BY', 'Plant', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Variance', 'DRIVEN_BY', 'Customer', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Variance', 'DRIVEN_BY', 'Material', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Variance', 'DRIVEN_BY', 'CostCenter', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Variance', 'DRIVEN_BY', 'GLAccount', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Risk', 'ABOUT', 'Variance', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Metric', 'MEASURED_BY', 'AnaplanLineItem', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('Metric', 'MEASURED_BY', 'SourceTable', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('AnaplanModule', 'HAS_LINE_ITEM', 'AnaplanLineItem', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('SourceTable', 'IMPLEMENTS', 'AccountingDocument', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('SourceTable', 'IMPLEMENTS', 'AccountingItem', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('SourceTable', 'IMPLEMENTS', 'Material', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('SourceTable', 'IMPLEMENTS', 'PurchaseOrder', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('SourceTable', 'IMPLEMENTS', 'SalesOrder', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('SourceTable', 'IMPLEMENTS', 'BillingDocument', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('SourceTable', 'IMPLEMENTS', 'ProductionOrder', 0);
INSERT INTO conformed.ontology_relationship_catalog (from_entity, relationship, to_entity, implemented) VALUES ('SourceTable', 'IMPLEMENTS', 'Asset', 0);
